added typehints
ultimaterpa/urpaform pull request #49
Opened 2021-09-08 14:46 UTC by Tscunami

Added typehints for each method
Also added docstring for init method inside Form class
Closing #18

2021-09-09 06:31 UTC, Slavaqq requested changes
Thank you. There are few things I want to change before I approve this pull requests.

2021-09-09 06:31 UTC, Slavaqq commented on urpaform/__init__.py
> +""" __init__.py """
How it relates to type hints?

2021-09-09 06:31 UTC, Slavaqq commented on urpaform/elements.py
> +        clear_keys: tuple = ("CTRL+A", "DEL"),
Use typing.Tuple

2021-09-09 06:31 UTC, Slavaqq commented on urpaform/form.py
> +    def add(self, *args: Union[Tuple[_FormElement, str], List[Tuple[_FormElement, str]]]) -> None:
List is too strict type.

2021-09-09 07:56 UTC, Tscunami commented
Thank you for your feedback. Check out my last commit 1b14b0a , all required changes are fixed here

2021-09-09 14:48 UTC, Tscunami commented on urpaform/__init__.py
> +""" __init__.py """
It doesn't relate, I decided to remove this.

2021-09-09 14:49 UTC, Tscunami commented on urpaform/form.py
> +    def add(self, *args: Union[Tuple[_FormElement, str], List[Tuple[_FormElement, str]]]) -> None:
I changed it from List to Iterable in the last commit.

2021-09-09 14:50 UTC, Tscunami commented on urpaform/elements.py
> +        clear_keys: tuple = ("CTRL+A", "DEL"),
I changed it to Tuple[str, str]

2021-09-10 06:39 UTC, Slavaqq approved these changes
Thank you

2021-09-10 06:39 UTC, merged