Added function to clear_clipboard_text
ultimaterpa/urpaform pull request #55
Opened 2021-09-14 08:41 UTC by Tscunami

Added function to clear_clipboard_text and added it to methods in urpaform, where we store text to clipboard

2021-09-20 12:56 UTC, anerold requested changes

2021-09-20 12:56 UTC, anerold commented on urpaform/form.py
> +        urpa.set_clipboard_text("")
no need setting it here. It is already done in method `complete()`

2021-09-20 13:26 UTC, Tscunami commented on urpaform/form.py
> +        urpa.set_clipboard_text("")
That's right, I removed it in the next commit.

2021-10-05 05:51 UTC, Slavaqq approved these changes

2021-10-05 05:52 UTC, merged